# Generated by Django 6.0.1 on 2026-01-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_answer_unique_question_and_choice_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_answer_question', 'Can answer question')]},
        ),
    ]
